server:
  port: 3344
spring:
  application:
    name: rongly-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/angiely1115/springcloud-config.git
          search-paths: '{application}'
