server:
  port: 8005
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka9000.com:9000/eureka/,http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/
spring:
  application:
    name: rongly-feign-demo
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
  threadpool:
    default:
      coreSize: 20
      maximumSize: 50
      allowMaximumSizeToDivergeFromCoreSize: true
#全局配置
ribbon:
  MaxAutoRetries: 0 # 对当前实例的重试次数
  MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
  OkToRetryOnAllOperations: false #重试操作
  ReadTimeout: 3000 # 请求处理的超时时间
  ConnectTimeout: 5000 # 请求连接超时时间
  #饥饿加载服务
  eager-load:
    enabled: true
    #不能配置*
    clients: rongly-dept,rongly-hystrix-demo
#单个应用服务配置 应用名称
rongly-hystrix-demo:
  ribbon:
    MaxAutoRetries: 0 # 对当前实例的重试次数
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    OkToRetryOnAllOperations: false #重试操作
    ReadTimeout: 5000 # 请求处理的超时时间
    ConnectTimeout: 5000 # 请求连接超时时间
spring_base_url: localhost:8080
#为单个服务设置负载路由规则
rongly-dept:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true #开启走okhttp接口
    #压缩配置
  compression:
    request:
     enabled: true
    response:
     enabled: true
rongly:
  okhttp:
    client:
      level: body
management:
  endpoints:
    web:
      exposure:
        include: env


