server:
  port: 8002
spring:
  application:
    name: rongly-ribbon-demo
eureka:
  client:
    #register-with-eureka: false
    service-url:
      defaultZone: http://eureka9000.com:9000/eureka/,http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/