server:
  port: 9999
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka9000.com:9000/eureka/,http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/
spring:
  application:
    name: rongly-zuul-demo
zuul:
  routes:
    mydept.serviceId: rongly-dept
    mydept.path: /rongly/dept/**
  ignored-services: rongly-dept #忽略用注册到eureka上的服务名称访问 "*" 表示忽略所有
  prefix: /rongly2 #配置访问统一的前缀 /不能少也不能与path路径前面相同了