server:
  port: 9999
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka9000.com:9000/eureka/,http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/
spring:
  application:
    name: rongly-zuul-demo
zuul:
  routes:
    mydept:
      serviceId: rongly-dept
      path: /rongly/dept/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization # 敏感的头部 切断与下层服务之间的交互
  ignored-services: rongly-dept #忽略用注册到eureka上的服务名称访问 "*" 表示忽略所有
  prefix: /rongly2 #配置访问统一的前缀 /不能少也不能与path路径前面相同了
  #禁用指定的filter
  SendErrorFilter.error.disable: true
  #使用线程隔离策略
  ribbon-isolation-strategy: THREAD
  thread-pool:
    #使用隔离的线程池
    use-separate-thread-pools: true
    #独立线程前缀
    thread-pool-key-prefix: zuul-gateway
  #开启饥饿加载
  ribbon:
    eager-load:
      enabled: true
  host:
    #每个路由可用的最大连接数
    max-per-route-connections: 50
    max-total-connections: 300
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
            #线程隔离 默认
          strategy: Thread
  threadpool:
    default:
      coreSize: 20
      maximumSize: 50
      allowMaximumSizeToDivergeFromCoreSize: true
#开启okhttp方式 不能都关了
ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
rongly:
  okhttp:
   client:
     level: body
#  ratelimit:
#    #按粒度拆分的临时变量key
#    key-prefix: springcloud-book
#    enabled: true
#    behind-proxy: true
#    repository: IN_MEMORY
#    default-policy-list:
#     limit: 2
#     quota: 1
#     refresh-interval: 3
#     type:
#      - user
#      - origin
#      - url




# repository: IN_EMMEORY #默认就是这个配置

management:
  endpoints:
    web:
      exposure:
        include: routes,filters
