spring:
  application:
    name: rongly-sso-web
  profiles:
    active: test
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    request-context-attribute: request
    cache: false
    settings:
      number_format: 0.##########
  redis:
    cluster:
      nodes:
      - 10.10.3.71:7000
      - 10.10.3.71:7001
      - 10.10.3.71:7002
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
  cache:
    redis:
      time-to-live: 10000s #默认过期时间 不设置默认永不过期
      use-key-prefix: false # 不使用cache-name:: 默认使用
server:
  port: 9091
  servlet:
    context-path: /xxl-sso-web
### xxl-sso
xxl:
  sso:
    server: http://localhost:9090/xxl-sso-server
    logout:
      path: /logout
    excluded:
      paths: /css/*,/static/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico,/reg
logging:
  file: ${spring.application.name}